### PR TITLE
Pixel buffer object capturer

### PR DESCRIPTION
**Pull request by daipenger**
Here I am again :)

An overview:

- Heavy memory optimization while recording:
You copied the ByteBuffer on the client memory side before giving it to the Exporter (not necessary)

- New PBOCapturer using two alternating pixel buffers for readback when supported by the GPU (Readback speed increased by about 8 times on a GTX 750 Ti)
This is a good ressource: http://www.songho.ca/opengl/gl_pbo.html

- New generalized ACapturer abstract class

- Using BGR color format for PipeExporter now, too
-> Internal OpenGL format
-> Stabilizes readback and ffmpeg handles it well
Requires new encoder arguments:
Lossy H264: "-f rawvideo -pix_fmt bgr24 -s %WIDTH%x%HEIGHT% -r %FPS% -i - -an -c:v libx264 -preset medium -qp 10 video.mp4"

### CODE REVIEW

**Comment by ata4** [comment]
Are you sure I created a copy of the byte buffer? IIRC, I used `ByteBuffer.duplicate()`, which actually just creates a new view of the original buffer, so there's barely any memory overhead. I used it to make sure the other modules don't interfere with the position of the buffer.

**Comment by daipenger** [comment]
Uhm, you are totally right o-O
No idea how I came to this conclusion and I was even still convinced about it when writing that comment.

**Comment by ata4** [comment]
Still, the PBO support is really good and brings a huge performance boost. I thought about that as well, but I wasn't sure how to implement it. Looks like you figured it out. :wink:

**Comment by ata4** [comment]
I found two issues so far:

* Complete code re-formatting, which is not really helping to be honest. I usually don't put `this` and `final` everywhere and I also prefer spaces over tabs for consistency. It's usually considered best practice to maintain the code style of the original author, but you're not the first contributor to my Minecraft mods who tries to enforce their own preferences. :wink:
* Every other frame appears to be a duplicate of the previous one for some reason. Any idea why?

**Comment by daipenger** [comment]
- I really did not want to enforce an own preference. On the one hand this was my first time contributing to a project and I did not think before making the first commits, even though I know about these good practices. The best solution would be to do a complete reformat of the project (clean up in eclipse) and make one huge commit which then brings your formatting back. On the other hand your project does not contain any project specific formatting scripts :/
- This is certainly some sort of forge bug/minecraft logic bug. It does appear when using both the old direct readback and PBOs. (Only difference: first frame is black when using PBOs but this is an issue which could be fixed easily)
But I remember that I always had to specify 2 times the amount of frames actually needed to assemble a video back in 1.8 versions. The thing was: My camera path tool has always used the RenderTickEvent. But back in the 1.8 versions minema could use the stream integration. I think that the RenderTickEvent is just called twice per frame. Good catch! :+1: So, it is time for a hardcoded drop of every other frame.

**Pull request merged**
